# Generated by Django 4.0.6 on 2022-07-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_shoe',
            field=models.BooleanField(default=True),
        ),
    ]
