# Generated by Django 4.0.6 on 2022-07-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_off', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.transaction'),
        ),
    ]
