# Generated by Django 4.0.6 on 2022-07-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0002_transaction_user_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transactions',
        ),
    ]
