# Generated by Django 4.0.6 on 2022-07-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0003_remove_user_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.user'),
        ),
    ]
