# Generated by Django 4.0.6 on 2022-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0004_transaction_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='admin',
        ),
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.ManyToManyField(to='wemes.transaction'),
        ),
    ]
