# Generated by Django 4.0.6 on 2022-07-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0005_remove_transaction_admin_user_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.user'),
        ),
    ]
