# Generated by Django 4.0.6 on 2022-07-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0006_remove_user_transactions_transaction_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_admin', to='wemes.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='wemes.user'),
        ),
    ]
