# Generated by Django 4.0.6 on 2022-07-29 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0009_color_department_remove_item_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wemes.transaction'),
        ),
    ]
