# Generated by Django 4.0.6 on 2022-07-29 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0012_alter_transaction_admin_alter_transaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='wemes.user'),
        ),
    ]
