# Generated by Django 4.0.6 on 2022-07-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0014_alter_transaction_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='transaction',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='item',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wemes.user'),
        ),
    ]
